exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
    hf_causal_model:
      - distilbert/distilgpt2
    
datafpath: ../midterm/language/english/data_file/long_vp_coord.tsv
predfpath: ../midterm/language/english/pred_file/long_vp_coord.tsv
resultsfpath: ../midterm/language/english/results_file/long_vp_coord.tsv

save: by_cond
